import Head from 'next/head'
import Image from 'next/image'
import styles from 'src/styles/Home.module.css'
import {Footer} from "src/components/Footer"
import { Main } from 'src/components/Main'
import { Header } from 'src/components/Header'
import { useCallback, useEffect } from 'react'


export default function Home() {

  const foo = 1;

  const handleClick = useCallback((e) => {
    console.log(e.target.href);
    e.preventDefault();
    alert(foo);
  }, [])


  useEffect( () => {
    document.body.style.backgroundColor = "lightblue";
    console.log("マウント");
    return () => {
      document.body.style.backgroundColor = "";
      console.log("アンマウント");
    }
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />

      <a
        href="/about"
        onClick={handleClick}
        >ボタン
      </a>

      <Main page="index" />

      <Footer />
    </div>
  );
}
