import Head from 'next/head'
import Image from 'next/image'
import styles from 'src/styles/Home.module.css'
import {Footer} from "src/components/Footer"
import { Main } from 'src/components/Main'
import { Header } from 'src/components/Header'
import { useCallback, useEffect, useState } from 'react'


export default function Home() {

  const [count, setCount] = useState(1);
  const [text, setText] = useState("");
  const [isShow, setIsShow] = useState(true);
  const [array, setArray] = useState([]);

  const handleClick = useCallback(() => {
    if(count<10) {
      setCount( prevCount => prevCount +1);
    }
  }, [count]);

  const handleChange = useCallback((e) => {
    if(e.target.value.length > 5){
      alert('5文字以内にしてください');
      return;
    }
      setText(e.target.value);
  }, [])

  const handleDisplay = useCallback(() => {
    setIsShow((prevIsShow) => !prevIsShow );
  }, []);

  useEffect( () => {
    document.body.style.backgroundColor = "lightblue";
    return () => {
      document.body.style.backgroundColor = "";
    }
  }, []);

  const handleAdd = useCallback( () => {
    setArray((prevArray) => {
      if(prevArray.some(item => item === text)) {
        alert('同じ要素が存在します。');
        return prevArray;
      }
      return [...prevArray, text];
    });
  }, [text]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      {isShow ? <h1>{count}</h1> : null}
      <button onClick={handleClick}>ボタン</button>
      <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>
      <button onClick={handleAdd}>追加</button>
      <input type="text" value={text}
      onChange = {handleChange}
      />

      <ul>
        {array.map(item => {
          return (
            <li key={item}>{item}</li>
          )
        })}
      </ul>

      <Main page="index" />

      <Footer />
    </div>
  );
}
